name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/docker-build.yml'

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: micro-deploy
  CONTAINER_NAME: micro-deploy

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.image.outputs.image }}
      image-tag: ${{ steps.image.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd app
          npm ci

      - name: Run Unit Tests
        run: |
          cd app
          npm test --if-present

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
          ./app

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Tag Docker Image
        run: |
          docker tag \
          ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
          ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          docker tag \
          ${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
          ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Push Docker Image
        run: |
          docker push \
          ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          docker push \
          ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Save Image URI
        id: image
        run: |
          echo "image=${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
